### ISSUE TITLE
no_allow lint rule

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/predicate-lang#55]
As explained in https://github.com/gravitational/predicate-lang/issues/51, a policy baseline is a good starting point to build a minimal linter.

`no_allow` rule lets policy administrator to forbid certain rules to be added to allow policy. When a new policy is created with matching forbidden rule, running linter will verify the rule using `Predicate.equivalent` and report back with details. Only allow rule will evaluated.

**Comment by flyinghermit** [comment]
Implemented with https://github.com/gravitational/predicate-lang/pull/61
